'use client'

import { Navbar } from '@/components/navbar'
import { Footer } from '@/components/footer'

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Navbar />

      <main className="flex-1">
        {/* Header Section */}
        <section className="py-20 px-4 sm:px-6 lg:px-8 bg-secondary">
          <div className="max-w-4xl mx-auto">
            <h1 className="text-5xl md:text-6xl font-bold text-secondary-foreground mb-4">Terms & Conditions</h1>
            <p className="text-lg text-secondary-foreground/90">Last Updated: February 18, 2026</p>
          </div>
        </section>

        {/* Content Section */}
        <section className="py-20 px-4 sm:px-6 lg:px-8">
          <div className="max-w-4xl mx-auto">
            <div className="space-y-8 text-foreground">
              <div>
                <h2 className="text-3xl font-bold text-secondary mb-4">1. Acceptance of Terms</h2>
                <p className="leading-relaxed mb-4">
                  These Terms and Conditions (this "Agreement") contain terms and conditions that govern your use of the Services provided by Waffles & More, and is a contract between JAY SHAILESHKUMAR MODI ("Waffles & More," "we," "us," or "our"), and you or the entity or organization that you represent.
                </p>
                <p className="leading-relaxed mb-4">
                  Waffles & More (hereinafter referred to as the "Platform," "Website," or "Waffles & More") is a food service business owned and operated by JAY SHAILESHKUMAR MODI (hereinafter referred to as "Waffles & More," "we," "us," or "our").
                </p>
                <p className="leading-relaxed mb-4">
                  This document is a legally binding document between the User of the Platform (hereinafter referred to as "You," "Your," and "User") and us in relation to the use of the platform and set forth the terms and conditions by which you may access and use the platform and our related websites, services, applications, products, and content (collectively, the "Services").
                </p>
                <p className="leading-relaxed mb-4">
                  If you are an individual using the Services: (1) all references to "Customer/you/your/user" are to you; and (2) you represent and warrant that you are at least 18 years of age or have otherwise reached the age of "majority" where you reside, and that you have the right, power, and authority to enter into this Agreement.
                </p>
                <p className="leading-relaxed mb-4">
                  By accessing or using the Platform or the Services, or by placing an order, you acknowledge that you have read, understood, and agree to be bound by this Agreement.
                </p>
                <p className="leading-relaxed">
                  This document is an electronic record in terms of the Information Technology Act, 2000, Digital Personal Data Protection Act, 2023, and rules framed thereunder, as applicable. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                </p>
              </div>

              <div>
                <h2 className="text-3xl font-bold text-secondary mb-4">2. Description of Services</h2>
                <p className="leading-relaxed mb-4">
                  Waffles & More provides food and beverage services including but not limited to:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Dine-in services at our physical locations</li>
                  <li>Takeaway and pickup services</li>
                  <li>Online ordering through third-party delivery platforms (Zomato, Swiggy)</li>
                  <li>Catering and event services</li>
                  <li>Product information and menu browsing through our website</li>
                </ul>
              </div>

              <div>
                <h2 className="text-3xl font-bold text-secondary mb-4">3. Orders and Payments</h2>
                <p className="leading-relaxed mb-4">
                  <strong>3.1 Order Placement:</strong> Orders can be placed in-store, via phone, or through authorized third-party delivery platforms. All orders are subject to availability.
                </p>
                <p className="leading-relaxed mb-4">
                  <strong>3.2 Pricing:</strong> All prices are listed in Indian Rupees (INR) and are subject to change without notice. Applicable taxes will be added to the final bill.
                </p>
                <p className="leading-relaxed mb-4">
                  <strong>3.3 Payment Methods:</strong> We accept cash, UPI, credit/debit cards, and payments through authorized delivery platforms. Payment is required at the time of order or delivery.
                </p>
                <p className="leading-relaxed">
                  <strong>3.4 Order Cancellation:</strong> Orders may be cancelled within a reasonable time before preparation begins. Once preparation has started, cancellations may not be possible. Refunds, if applicable, will be processed according to our refund policy.
                </p>
              </div>

              <div>
                <h2 className="text-3xl font-bold text-secondary mb-4">4. Intellectual Property Rights</h2>
                <p className="leading-relaxed">
                  All rights, title, and interest in and to the Platform, Website, brand name, logos, recipes, and content, including all intellectual property rights, are and will remain the exclusive property of Waffles & More and JAY SHAILESHKUMAR MODI. You receive no rights other than those explicitly granted in this Agreement.
                </p>
              </div>

              <div>
                <h2 className="text-3xl font-bold text-secondary mb-4">5. User Obligations and Restrictions</h2>
                <p className="leading-relaxed mb-4">
                  You agree not to misuse the Services. Prohibited activities include:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Providing false or misleading information</li>
                  <li>Using the services for any illegal or unauthorized purpose</li>
                  <li>Attempting to gain unauthorized access to our systems</li>
                  <li>Reproducing, duplicating, copying, or reselling any part of our services</li>
                  <li>Harassing or causing distress to our staff or other customers</li>
                  <li>Posting defamatory, offensive, or inappropriate content</li>
                </ul>
              </div>

              <div>
                <h2 className="text-3xl font-bold text-secondary mb-4">6. Food Safety and Allergies</h2>
                <p className="leading-relaxed mb-4">
                  <strong>6.1 Food Safety:</strong> We maintain high standards of food safety and hygiene. All our products are prepared in accordance with applicable food safety regulations.
                </p>
                <p className="leading-relaxed mb-4">
                  <strong>6.2 Allergen Information:</strong> Our menu items may contain common allergens including dairy, nuts, eggs, gluten, and soy. Please inform our staff of any allergies or dietary restrictions when placing your order.
                </p>
                <p className="leading-relaxed">
                  <strong>6.3 Customer Responsibility:</strong> It is the customer's responsibility to communicate any dietary restrictions or allergies. Waffles & More shall not be liable for any adverse reactions resulting from undisclosed allergies or dietary requirements.
                </p>
              </div>

              <div>
                <h2 className="text-3xl font-bold text-secondary mb-4">7. Cancellation and Refund Policy</h2>
                <p className="leading-relaxed mb-4">
                  <strong>7.1 In-Store Orders:</strong> In-store orders once prepared cannot be cancelled or refunded unless there is a quality issue with the product.
                </p>
                <p className="leading-relaxed mb-4">
                  <strong>7.2 Delivery Orders:</strong> Orders placed through third-party delivery platforms are subject to the cancellation and refund policies of those platforms.
                </p>
                <p className="leading-relaxed">
                  <strong>7.3 Quality Issues:</strong> If you receive a product that is damaged, defective, or not as described, please contact us immediately. We will assess the issue and provide a replacement or refund as appropriate.
                </p>
              </div>

              <div>
                <h2 className="text-3xl font-bold text-secondary mb-4">8. Limitation of Liability</h2>
                <p className="leading-relaxed mb-4">
                  Waffles & More shall not be liable for indirect, incidental, special, or consequential damages, including loss of profits, arising from the use or inability to use the Services, except as required by law.
                </p>
                <p className="leading-relaxed">
                  Our total liability to you for any claim arising out of or relating to this Agreement shall not exceed the amount paid by you for the specific product or service giving rise to the claim.
                </p>
              </div>

              <div>
                <h2 className="text-3xl font-bold text-secondary mb-4">9. Force Majeure</h2>
                <p className="leading-relaxed">
                  Waffles & More shall not be responsible for delays or failure to perform due to events beyond its reasonable control, including natural disasters, acts of God, pandemic, war, labor strikes, power outages, equipment failure, or supply chain disruptions.
                </p>
              </div>

              <div>
                <h2 className="text-3xl font-bold text-secondary mb-4">10. Prohibited Items and Activities</h2>
                <p className="leading-relaxed mb-4">
                  The following are strictly prohibited on our premises and through our services:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Illegal drugs, narcotic substances, or controlled substances</li>
                  <li>Weapons, firearms, or dangerous objects</li>
                  <li>Stolen property or counterfeit goods</li>
                  <li>Items that violate intellectual property rights</li>
                  <li>Obscene, offensive, or pornographic materials</li>
                  <li>Any items prohibited by applicable Indian laws</li>
                  <li>Activities that disrupt business operations or harm other customers</li>
                </ul>
              </div>

              <div>
                <h2 className="text-3xl font-bold text-secondary mb-4">11. Governing Law and Jurisdiction</h2>
                <p className="leading-relaxed">
                  This Agreement shall be governed by and construed in accordance with the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts of Bharuch, Gujarat.
                </p>
              </div>

              <div>
                <h2 className="text-3xl font-bold text-secondary mb-4">12. Modifications to Terms</h2>
                <p className="leading-relaxed">
                  We reserve the right to modify these Terms and Conditions at any time. Changes will be posted on this page with an updated "Last Updated" date. Your continued use of our services after any changes constitutes acceptance of the modified terms. We encourage you to review these terms periodically.
                </p>
              </div>

              <div>
                <h2 className="text-3xl font-bold text-secondary mb-4">13. Severability</h2>
                <p className="leading-relaxed">
                  If any provision of this Agreement is found to be invalid or unenforceable, the remaining provisions shall continue in full force and effect.
                </p>
              </div>

              <div>
                <h2 className="text-3xl font-bold text-secondary mb-4">14. Entire Agreement</h2>
                <p className="leading-relaxed">
                  This Agreement, together with our Privacy Policy, constitutes the entire agreement between you and Waffles & More regarding your use of our services and supersedes all prior agreements and understandings.
                </p>
              </div>

              <div>
                <h2 className="text-3xl font-bold text-secondary mb-4">15. Contact Us</h2>
                <p className="leading-relaxed mb-4">
                  If you have any questions or concerns regarding these Terms and Conditions, please contact us:
                </p>
                <div className="bg-gray-800 p-6 rounded-lg">
                  <p className="leading-relaxed">
                    <strong className="text-primary">Waffles & More</strong>
                    <br />
                    <strong>Owned & Operated by JAY SHAILESHKUMAR MODI</strong>
                    <br />
                    Shop No. 2, Nagarpalika Shopping Centre, Civil Road, Bharuch, Gujarat – 392001
                    <br />
                    Phone: +91 94996 78796
                    <br />
                    Instagram: @_wafflesandmore_
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  )
}
